if [[ "$OSTYPE" == "darwin"* ]]; then
  bazel coverage --config=macos //...
else
  bazel coverage //...
fi
genhtml --filter brace --branch-coverage --output  coverage_output "$(bazel info output_path)/_coverage/_coverage_report.dat"
