name: FXTrading-Repo-Workflow

on:
  pull_request:
    branches:
      - 'main'
    types: [synchronize, reopened, closed, opened]

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  WorkflowMeta:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    outputs:
      latest_commit_message: ${{ steps.action_meta_info.outputs.commit_message }}
      git_short_sha: ${{ steps.action_meta_info.outputs.SHORT_SHA }}
      branch_name: ${{ steps.action_meta_info.outputs.BRANCH_NAME }}

    steps:
    - name: Get current commit message
      id: action_meta_info
      run: |
        if [[ '${{ github.event.pull_request.merged }}' == 'true' ]]; then
          compare_to=origin/main^
        else
          compare_to=origin/main
        fi
        echo "$(git log ${compare_to}..HEAD --oneline | sed -n 2p)"
        commit_message=$(git log ${compare_to}..HEAD --oneline | sed -n 2p)
        echo "commit_message=${commit_message}" >> $GITHUB_OUTPUT
        echo ${commit_message}
        echo "SHORT_SHA=`echo $(git log ${compare_to}..HEAD --oneline | sed -n 2p | cut -d ' ' -f1)`" >> $GITHUB_OUTPUT
        echo "BRANCH_NAME=`echo ${GITHUB_REF_NAME} | tr / _`" >> $GITHUB_OUTPUT

  SimulatorWorkflow:
    uses: ./.github/workflows/simulator_workflow.yaml

  workflow-success:
    runs-on: ubuntu-latest
    needs:
      - WorkflowMeta
      - SimulatorWorkflow
    if: always()
    steps:
    - name: Check Statuses
      run: |
        if [[ "${{ github.event.pull_request.draft }}" != 'false']]; then
          echo "switching from draft can cause an erroneous pass of the actions. Push a new commit or reopen."
          exit 1
        fi
        for result in \
          ${{ needs.WorkflowMeta.result}} \ 
          ${{ needs.SimulatorWorkflow.result }}

          do 
            if [[ $result != "success" && $result != "skipped" ]]; then
              exit 1
            fi
          done
