name: Simulator Workflow

on:
  workflow_call:
    inputs: {}
    outputs: {}
    secrets: {}

jobs:
  simulator-workflow:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: false
        fetch-depth: 0
    - name: Get PR metadata
      uses: ./.github/actions/action_meta
    - name: upgrade clang-format
      run: |
        pip install clang-format
        echo "$(clang-format --version)"
    - name: Install lcov
      run: |
        sudo apt-get update && apt-get install lcov
    - name: formatting and linting
      run: |
        make format-check
    - name: run test coverage
      run: |
        mkdir coverage_output && make coverage >> coverage_output/coverage.info
        LINES_COVERED=$(cat coverage_output/coverage.info | awk '/lines\.\.\./ {print $2}' | tr -d '%')
        REQUIRED_COVERAGE=100
        if (( $(echo "$LINES_COVERED < $REQUIRED_COVERAGE" | bc -l) )); then
          echo "Coverage is below $REQUIRED_COVERAGE%! Failing the build."
          exit 1
        fi
